[env:m5stickc-plus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
board_build.f_cpu = 160000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5StickCPlus
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0

[env:cardputer-adv]
platform = espressif32
board = m5stack-stamps3   ; Cardputer is a StampS3-based device
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCARDPUTER_ADV
    -DBOARD_HAS_PSRAM
build_src_filter = +<*> +<buddies/>
extra_scripts = post:scripts/merge_bin.py
lib_deps =
    m5stack/M5Unified @ ^0.2.0
    m5stack/M5Cardputer @ ^1.0.3
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
